### ISSUE TITLE
Mixed line endings in generated files - "npm test" fails on eslint

### ISSUE THREAD

**Issue by iva2k** [feathers-plus/cli#5] opened 2018-07-17 04:41 UTC
Using Windows7, node v8.11.2, Performed the following steps from [https://generator.feathers-plus.com/get-started/](https://generator.feathers-plus.com/get-started/)

```bash
npm i -g @feathers-plus/cli
mkdir feathers-app
cd feathers-app
feathers-plus generate options
# chosen all defaults

feathers-plus generate app
# chosen all defaults

npm start
# -> runs ok
```

Trying test:
```
npm test > log.test 2>&1
```

Test fails in eslint step, here's the result:

log.test
```
> api-1@0.0.0 test C:\dev\ionic3-feathersplus-try2\api1
> npm run eslint && npm run mocha


> api-1@0.0.0 eslint C:\dev\ionic3-feathersplus-try2\api1
> eslint src/. test/. --config .eslintrc.json


C:\dev\ionic3-feathersplus-try2\api1\src\app.hooks.js
   4:28  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   5:36  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   8:25  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   9:43  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  10:29  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  16:31  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  17:20  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  18:14  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  19:13  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  20:16  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  21:16  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  22:15  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  23:15  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  28:30  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  29:20  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  30:14  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  31:13  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  32:16  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  33:16  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  34:15  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  35:15  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  40:30  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  41:20  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  42:14  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  43:13  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  44:16  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  45:16  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  46:15  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  47:15  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

C:\dev\ionic3-feathersplus-try2\api1\src\app.js
  30:32  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  31:43  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

C:\dev\ionic3-feathersplus-try2\api1\src\index.js
  14:46  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  15:63  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  21:36  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  22:86  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

C:\dev\ionic3-feathersplus-try2\api1\src\logger.js
   9:28  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  10:56  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  11:17  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  13:29  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  14:26  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  15:20  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  16:20  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  17:5   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  19:32  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  20:16  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  21:29  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  22:5   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

C:\dev\ionic3-feathersplus-try2\api1\src\models\users.model.js
  10:34  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  11:25  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  12:45  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  13:19  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  14:6   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  15:59  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

C:\dev\ionic3-feathersplus-try2\api1\src\services\users\users.hooks.js
   3:54  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   4:70  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   5:43  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   9:25  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  10:43  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  11:29  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  18:34  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  19:37  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  20:37  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  21:32  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  22:53  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  23:53  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  25:31  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  26:13  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  27:35  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  28:34  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  29:32  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  30:53  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  31:52  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  32:36  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  37:34  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  39:30  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  40:69  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  41:14  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  42:13  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  43:16  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  44:16  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  45:15  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  46:15  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  51:30  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  52:13  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  53:14  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  54:13  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  55:16  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  56:16  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  57:15  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  58:15  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

C:\dev\ionic3-feathersplus-try2\api1\src\services\users\users.mongo.js
   9:28  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  18:5   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

C:\dev\ionic3-feathersplus-try2\api1\src\services\users\users.mongoose.js
  11:28  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  12:6   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

C:\dev\ionic3-feathersplus-try2\api1\src\services\users\users.schema.js
   8:36   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   9:18   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  10:34   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  34:29   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  35:18   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  36:15   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  37:24   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  38:7    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  39:14   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  40:28   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  41:27   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  42:22   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  43:42   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  44:12   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  45:10   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  51:38   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  52:116  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

C:\dev\ionic3-feathersplus-try2\api1\src\services\users\users.sequelize.js
  18:38  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  19:6   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

C:\dev\ionic3-feathersplus-try2\api1\src\services\users\users.validate.js
  10:32  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  11:43  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  12:21  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  16:27  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  23:5   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  47:34  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  48:47  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  53:34  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  54:47  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  59:33  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  60:46  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

✖ 124 problems (124 errors, 0 warnings)
  124 errors, 0 warnings potentially fixable with the `--fix` option.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! api-1@0.0.0 eslint: `eslint src/. test/. --config .eslintrc.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the api-1@0.0.0 eslint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\iivanchenko\AppData\Roaming\npm-cache\_logs\2018-07-17T04_32_21_344Z-debug.log
npm ERR! Test failed.  See above for more details.

```

Running --fix corrects line endings and tests pass:
```
npm run eslint -- --fix
```

Regenerating users service breaks tests again with same CRLF mix:

```
feathers-plus generate service
npm test
# -> eslint fails again
```

**Comment by eddyystop** [comment] 2018-07-17 12:55
Thanks for the heads up.

**Comment by eddyystop** [comment] 2018-07-17 15:01
@iva2k please confirm the issue is that most of the line endings are LR, which is acceptable, but some are CRLF.

**Comment by eddyystop** [comment] 2018-07-17 17:05
Fix pushed to GitHub.

Will be published in the next few days as @feathers-plus/cli 0.4.13.

**Comment by eddyystop** [comment] 2018-07-17 18:37
f+/cli 0.4.13 published.

**Comment by eddyystop** [comment] 2018-07-18 11:57
I'm closing this as https://github.com/feathers-plus/cli/issues/8 has been created.

**Closed by eddyystop** 2018-07-18 11:57 UTC
Labels: bug
